/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.afecioru.apps;

public class BasicThreads {
    private static class ProcessingThread  extends Thread {
        private final String name;
        ProcessingThread(String name) {
            this.name = name;
        }

        @Override
        public void run() {
            for (int i = 0; i < 100; i++) {
                System.out.println("[" + name +"] Processing: " + i);

                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    }


    public static void main(String[] args) throws InterruptedException {
        // create and start the threads
        ProcessingThread t1 = new ProcessingThread("TH-1");
        ProcessingThread t2 = new ProcessingThread("TH-2");

        t1.start();
        t2.start();

        // in the main thread, wait for both child threads to finish
        t1.join();
        t2.join();

        System.out.println("Done.");
    }
}
